# Generated by Django 5.2.4 on 2025-07-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="timestamp",
            new_name="dt_inclusao",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="expression",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="result",
        ),
        migrations.AddField(
            model_name="operation",
            name="parametros",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operation",
            name="resultado",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
